services:
  - type: web
    name: filmolog-bot
    runtime: python
    plan: free
    region: oregon
    buildCommand: pip install -e .
    startCommand: python -m movie_bot.main
    envVars:
      - key: BOT_TOKEN
        fromSecret: BOT_TOKEN